# Generated by Django 4.0.4 on 2022-05-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.TextField(max_length=50, verbose_name='Nombre Producto')),
                ('marca', models.TextField(verbose_name='Marca')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='Products', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
