# Generated by Django 4.0.4 on 2022-05-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='idProducto',
            field=models.IntegerField(null=True, verbose_name='Id Producto'),
        ),
    ]
