# Generated by Django 4.0.4 on 2022-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_products_idproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='Producto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('unit', models.TextField(verbose_name='Unidad')),
                ('price', models.IntegerField(verbose_name='Valor')),
                ('image', models.ImageField(upload_to='products', verbose_name='Imagen')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('update', models.DateField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['created'],
            },
        ),
    ]
