# Generated by Django 4.0.4 on 2022-05-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
