# Generated by Django 4.0.4 on 2022-05-21 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'permissions': (('Bodeguero', 'P_Bodeguero'), ('Vendedor', 'P_Vendedor'), ('Cliente', 'P_Cliente'), ('Contador', 'P_Contador')), 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
