# Generated by Django 4.0.4 on 2022-05-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEnvio', models.IntegerField(verbose_name='Id Envio')),
                ('cliente', models.TextField(verbose_name='Nombre Cliente')),
                ('direccion', models.TextField(max_length=100, verbose_name='Direccion')),
                ('ciudad', models.TextField(verbose_name='Ciudad')),
                ('comuna', models.TextField(verbose_name='Comuna')),
                ('indicaciones', models.TextField(null=True, verbose_name='indicaciones')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('update', models.DateField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'envio',
                'verbose_name_plural': 'envios',
            },
        ),
    ]
