# Generated by Django 4.0.4 on 2022-05-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='created',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='update',
        ),
        migrations.AlterField(
            model_name='envio',
            name='idEnvio',
            field=models.IntegerField(null=True, verbose_name='Id Envio'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='indicaciones',
            field=models.TextField(blank=True, null=True, verbose_name='indicaciones'),
        ),
    ]
