# Generated by Django 4.0.4 on 2022-06-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_envio_created_remove_envio_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.IntegerField(null=True, verbose_name='Id Envio')),
                ('cliente', models.TextField(verbose_name='Nombre Cliente')),
                ('correo', models.TextField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
    ]
